<?php
// $Id$

/**
 * @file
 * Facebook-style statuses gives each user a status that they can update and others can view.
 *
 * The module provides a number of blocks and integration with other modules to maximize usability.
 * In addition, several convenient hooks are provided to facilitate custom blocks.
 */

/**
 * Implementation of hook_help().
 */
function facebook_status_help($path='', $arg) {

  $output = '';

  switch ($path) {
    case "admin/help#facebook_status":
      $output = '<p>'. t("This module adds a Facebook-style status block.  Please see <a href=\"http://drupal.org/project/facebook_status\" title=\"http://drupal.org/project/facebook_status\" rel=\"nofollow\">http://drupal.org/project/facebook_status</a> for more information.") .'</p>';
      break;
  }

  return $output;
}

/**
 * Implementation of hook_form_alter().
 */
function facebook_status_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_admin_configure' && arg(4) == 'facebook_status' && (arg(5) == '3' || arg(5) == '4')) {
    $form['facebook_status'] = array(
      '#type' => 'fieldset',
      '#title' => t('Facebook Status Settings'),
      '#collapsible' => TRUE,
      '#weight' => -4,
      '#tree' => TRUE,
    );
  }
  if ($form_id == 'block_admin_configure' && arg(4) == 'facebook_status' && arg(5) == '3') {
    $form['facebook_status']['facebook_status_special_user'] = array(
      '#type' => 'textfield',
      '#title' => t('User ID of the user whose statuses you want to display in this block'),
      '#default_value' => variable_get('facebook_status_special_user', 1),
      '#size' => 12,
      '#maxlength' => 11,
      '#description' => t("This block will work exactly like the Facebook Status block, except that it only shows one user's status.  That user is determined by the UID you enter in this field."),
      '#element_validate' => array('facebook_status_alter_validate'),
    );
  }
  if ($form_id == 'block_admin_configure' && arg(4) == 'facebook_status' && arg(5) == '4') {
    $fbsur = facebook_status_rel_types();
    $form['facebook_status']['facebook_status_ur_type'] = array(
      '#type' => 'select',
      '#title' => t('Relationship type to use for this block'),
      '#default_value' => variable_get('facebook_status_ur_type', 1),
      '#description' => t("This block works exactly like the Facebook Status Recent Updates block except that it only shows the latest status updates for users with whom the currently logged in user has a relationship."),
      '#options' => $fbsur,
    );
  }
}

/**
 * Implementation of hook_validate().
 *
 * @see facebook_status_form_alter()
 */
function facebook_status_alter_validate($form, &$form_state) {
  if ( !is_numeric($form_state['values']['facebook_status']['facebook_status_special_user']) || $form_state['values']['facebook_status']['facebook_status_special_user'] <= 0 ) {
    form_set_error('', t('Please enter a single User ID in the Facebook Status UID field.  The UID of the user you enter will be used to determine which user to use for this block.'));
  }
  else if ( !db_result(db_query("SELECT created FROM {users} WHERE uid = %d", $form_state['values']['facebook_status']['facebook_status_special_user'])) ) {
    form_set_error('', t('The value you have entered in the Facebook Status UID field is not a valid User ID.  The UID is the number that appears in the URL on profile pages after "/user/".'));
  }
}

/**
 * Implementation of hook_perm().
 */
function facebook_status_perm() {
  //Note that, since all this module does is provide a block, there is no need for an 'access facebook_status' permission because access can be set in the block's settings.
  return array('edit own facebook_status', 'edit all facebook_status');
}

/**
 * Implementation of hook_block().
 */
function facebook_status_block($op='list', $delta=0) {
  if ($op == "list") {
    $block[0]["info"] = t("Facebook Status");
    $block[1]["info"] = t("Facebook Status Recent Updates");
    $block[2]["info"] = t("Facebook Status User Update History");
    $block[3]["info"] = t("Facebook Status Individual User");
    if (module_exists('user_relationships')) {
      $block[4]["info"] = t("Facebook Status UR Recent Updates");
    }
    return $block;
  }
  else if ($op == 'view') {
    global $user;
    switch ($delta) {
    case 0:
    case 3:
      $block['subject'] = 'Status';
      $block['content'] = facebook_status_display_b(NULL, 0, $delta);
      break;
    case 1:
      $x = -1;
    case 2:
      //If we're displaying the User Update History block, we need to send the right UID to facebook_status_get_status instead of -1 which gets all users.
      if ($delta == 2) {
        if ( arg(0) == 'user' && is_numeric(arg(1)) ) {
          $x = arg(1);
        }
        else if ( arg(0) == 'node' && is_numeric(arg(1)) ) {
          $x = db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1)));
        }
        else {
          $x = $user->uid;
        }
      }
      if (!in_array($x, variable_get('facebook_status_clear_user', array(0)))) {
        $c_array = facebook_status_get_status($x, variable_get('facebook_status_max_num_block_stats_all', 5));
        $block_content = "<div class='facebook_status_block_all'>". facebook_status_list_render($c_array) ."</div>";
      }
      $block['subject'] = "Recent Status Updates";
      $block['content'] = $block_content;
      break;
    case 4:
      //This module_exists() may not be necessary because $block[4]["info"] is also wrapped in module_exists().
      if (module_exists('user_relationships')) {
        $subject = db_result(db_query("SELECT plural_name FROM {user_relationship_types} WHERE rtid = %d", variable_get('facebook_status_ur_type', 1)));
        $content = facebook_status_get_rel_status();
        $content = facebook_status_list_render($content);
        if ($content) {
          $content = '<div class="facebook_status_block_rel">'. $content .'</div>';
        }
        $block['subject'] = $subject . t("' Recent Status Updates");
        $block['content'] = $content;
      }
      break;
    }
    return $block;
  }

}

function facebook_status_get_rel_status($ur_rtid = -1, $number = 0, $grouping = TRUE) {
  if (module_exists('user_relationships')) {
    return facebook_status_get_ur_status($ur_rtid, $number, $grouping);
  }
  return;
}

/**
 * FAPI definition for the status update form.
 *
 * facebook_status_form_display() renders the form via drupal_get_form().
 *
 * @param $uid
 *   A UID to use for the update form.  If no UID the function automatically decides which one to use.
 * @ingroup forms
 * @see facebook_status_update_submit()
 * @see facebook_status_update_validate()
 */
function facebook_status_update($form_state = NULL, $uid = 0) {
  if (!$uid) {
    global $user;
  }
  else {
    $user = user_load(array('uid' => $uid));
  }
  if (variable_get('facebook_status_mode', 1)) {
    if (arg(0) == 'user' && is_numeric(arg(1)) && !$uid) {
      $user2 = user_load(array('uid' => arg(1)));
      $xname = theme('username', $user2);
    }
    else if (arg(0) == 'node' && is_numeric(arg(1)) && !$uid) {
      $uuid = db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1)));
      $user2 = user_load(array('uid' => $uuid));
      $xname = check_plain($user2->name);
      if ($uuid != $user->uid) {
        $xname = theme('username', $user2);
      }
    }
    else if (!$uid) {
      $xname = theme('username', $user);
    }
    else {
      $xname = theme('username', $user);
    }
    $title = '';
  }
  else {
    $xname = '';
    $title = t("Status");
  }
  $status = facebook_status_get_status($uid);
  //Warning: the status column in the {facebook_status} table only holds 255 bytes.
  //In strict SQL mode, statuses larger than this will not be saved; in other modes, they will be truncated.
  //This is relevant for the #maxlength attribute; do not set a #maxlength larger than the column can hold.
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => $title,
    '#field_prefix' => '<span style="float: left;">'. $xname .'&nbsp; </span>',
    '#size' => variable_get('facebook_status_field_length', 30),
    '#maxlength' => variable_get('facebook_status_length', 192),
    '#description' => t("Please enter your status.  Remember that it will not update unless you click 'Save.'"),
    '#default_value' => ((!empty( $status[0]['status_fb'] ) ) ? check_plain($status[0]['status_fb']) : t("is ")),
  );
  $form['uid'] = array('#type' => 'hidden', '#value' => $uid);
  $form['submit'] = array('#type' => 'submit', '#value' => t("Save") );
  return $form;
}

/**
 * Renders themed HTML for the status update form.
 */
function facebook_status_form_display($form_state = NULL, $uid = 0) {
  return drupal_get_form('facebook_status_update', $form_state, $uid);
}

/**
 * Themes status update form block.
 */
function facebook_status_display_b($form_state = NULL, $uid = 0, $delta = 0) {
  global $user;
  if (!$uid) {
    $account = $user;
  }
  else {
    $account = user_load(array('uid' => $uid));
  }
  $x = FALSE;
  //Get the information before we decide whether to show the update form so we can check to make sure we don't show the form to people it shouldn't be shown to.
  //It doesn't matter whether the user is allowed to have a status because if the user isn't allowed, the status just won't show up (we address this later on).
  if (arg(0) == 'user' && is_numeric(arg(1)) && !$uid) {
    $account2 = user_load(array('uid' => arg(1)));
    $fbs_name = check_plain($account2->name);
    $fbs_uid = arg(1);
    $sm = db_fetch_array(db_query_range("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", arg(1), 0, 1));
  }
  else if (arg(0) == 'node' && is_numeric(arg(1)) && !$uid) {
    $fbs_uid = db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1)));
    $account2 = user_load(array('uid' => $fbs_uid));
    $fbs_name = check_plain($account2->name);
    $sm = db_fetch_array(db_query_range("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid, 0, 1));
  }
  else {
    $fbs_name = check_plain($account->name);
    $fbs_uid = $account->uid;
    $sm = db_fetch_array(db_query_range("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $account->uid, 0, 1));
  }
  $block_content = '<div class="facebook_status_block">';
  //This gigantic 'if' statement decides whether we can show the update form or not.  And if we don't show the form, we don't need the AJAX.
  if ((( (((arg(0) == 'user' && is_numeric(arg(1)) && arg(1) == $account->uid)
    || (arg(0) == 'node' && is_numeric(arg(1)) && db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1))) == $account->uid)
    || (arg(0) != 'user' && arg(0) != 'node' && !is_numeric(arg(1)))
    || (drupal_is_front_page()))
    && user_access('edit own facebook_status')
    && !in_array($account->uid, variable_get('facebook_status_clear_user', array(0))))
    || (user_access('edit all facebook_status')
    && !in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0)))) ) && !$uid)
    || ((($uid == $user->uid && user_access('edit own facebook_status')) || (user_access('edit all facebook_status') && $uid))
    && !in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0))))) {
    $block_content .= '<div class="facebook_status_form">'. facebook_status_form_display($form_state, $uid) .'</div>';
    $x = TRUE;
    $path = drupal_get_path('module', 'facebook_status');
    if (variable_get('facebook_status_ajax', 1)) {
      drupal_add_js($path .'/facebook_status.js');
    }
  }
  //On the block that shows only the "special user" status, assign the special user using the value set on the block configuration form (see facebook_status_form_alter).
  //We're just going to assume that this user isn't on the list of users who aren't allowed to have statuses.  If this user is on that list, we'll set the updated time to now and the status to an error.
  if ($delta == 3) {
    $fbs_uid = variable_get('facebook_status_special_user', 1);
    $account2 = user_load(array('uid' => $fbs_uid));
    $fbs_name = check_plain($account2->name);
    if (in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0)))) {
      $sm['status_fb'] = t("Error: this user is not allowed to have a status.");
      if (user_access('access administration pages')) {
        $sm['status_fb'] .= l(t('  Change this'), 'admin/settings/facebook_status');
      }
      $sm['status_time'] = time();
    }
    else {
      $sm = db_fetch_array(db_query_range("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid, 0, 1));
    }
  }
  $block_content .= '<div class="facebook_status_status">';
  if ($x) {
    //If the form is going to show up (i.e. if a user can edit their status) then apply 'a' formatting to the status so it looks clickable so users are aware that the form will appear using AJAX.
    $block_content .= '<a class="facebook_status_ajax_clickable_text">';
  }
  if ($sm['status_time'] && !in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0)))) {
    if (variable_get('facebook_status_mode', 1)) {
      //If the status is not edit-able, make the user's name a link to that user's profile.
      if ($x || (arg(0) == 'user' && is_numeric(arg(1)))) {
        $block_content .= $fbs_name ." ";
      }
      else {
        $block_content .= l($fbs_name, "user/". $fbs_uid) ." ";
      }
    }
    if (time() - $sm['status_time'] < 60) {
      $time = t("a moment");
    }
    else {
      $time = format_interval(time() - $sm['status_time'], 1);
    }
    $block_content .= check_plain($sm['status_fb']);
    if ($x) {
      $block_content .= '</a>';
    }
    $block_content .= t(" <span class='submitted'>!time ago</span>", array('!time' => $time));
  }
  //If the user is not allowed to have a status.
  else if (in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0)))) {
    //If the status form is not the user's own, use different strings than if it is the user's own.
    if ( $fbs_uid != $account->uid ) {
      $block_content .= t('@username is not allowed to have a status.', array('@username' => $fbs_name));
    }
    else {
      $block_content .= t('You are not allowed to have a status.');
    }
    if (user_access('access administration pages')) {
      $block_content .= l(t('  Change this'), 'admin/settings/facebook_status');
    }
  }
  //If the user has not posted a status.
  else {
    //If the status form is not the user's own, use different strings than if it is the user's own.
    if ( $fbs_uid != $account->uid || $uid ) {
      $block_content .= t('@username does not yet have a status', array('@username' => $fbs_name));
    }
    else {
      $block_content .= t('You do not yet have a status');
    }
    if ($x) {
      $block_content .= '</a>';
    }
  }
  $block_content .= '</div></div>';
  return $block_content;
}

/**
 * FAPI submit function for facebook_status_update().
 * Implementation of hook_submit().
 *
 * There are separate sections for the different permission types because it's easier to read and runs a little faster
 * than if only the 'edit all' section was used and permissions were checked each time before setting $uid.
 * The result is that the code is slightly longer and so more is loaded on bootstrap.
 * This is all technically unnecessary in terms of this module because the form doesn't render if it can't be used,
 * but it saves a lot of work for anyone who decides to render the form arbitrarily.
 *
 * Indentation is slightly irregular because permission checking was added after most of the code was written.
 *
 * @see facebook_status_update()
 * @see facebook_status_update_validate()
 */
function facebook_status_update_submit($form, &$form_state) {
  global $user;
      //Note that this first part is only for people who can edit their own status, so we don't need to check whose database records to update.
      if ( user_access('edit own facebook_status') && !user_access('edit all facebook_status') ) {
  if ( db_query("INSERT INTO {facebook_status} (status_fb, status_time, uid) VALUES('%s', %d, %d)", $form_state['values']['name'], time(), $user->uid) ) {
    if (module_exists('notice')) {
      fbs_notice_insert($user->uid);
    }
    drupal_set_message(t('Your status has been updated.'));
  }
  else {
    drupal_set_message(t('An error has occurred while updating your status.  Please try again.  If the problem persists, please contact an administrator.'), 'error');
  }
      }
      else if (user_access('edit all facebook_status')) {
  //Determine the uid of the user whose status will be updated.
  $uid = $form_state['values']['uid'];
  if (!$uid) {
    if ( arg(0) == 'user' && is_numeric(arg(1)) ) {
      $uid = arg(1);
    }
    else if ( arg(0) == 'node' && is_numeric(arg(1)) ) {
      $uid = db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1)));
    }
    else {
      $uid = $user->uid;
    }
  }
  if ($uid != $user->uid) {
    $user2 = user_load(array('uid' => $uid));
    $message = t("!name's status has been updated.", array('!name' => theme('username', $user2)));
  }
  else {
    $message = t('Your status has been updated.');
  }
  if ( db_query("INSERT INTO {facebook_status} (status_fb, status_time, uid) VALUES('%s', %d, %d)", $form_state['values']['name'], time(), $uid) ) {
    drupal_set_message($message);
    if (module_exists('notice')) {
      fbs_notice_insert($user->uid);
    }
  }
  else {
    drupal_set_message(t('An error has occurred while updating the status.  Please try again.'), 'error');
  }
      }
      //This technically shouldn't happen, but we need a catch in case someone without permission manages to submit the form.
      else {
        drupal_set_message(t('An error has occurred while updating the status: you do not have permission to perform this action.  Please contact an administrator.'), 'error');
      }
}

/**
 * FAPI validate function for facebook_status_update().
 * Implementation of hook_validate().
 *
 * There are separate sections for the different permission types because it's easier to read and runs a little faster
 * than if only the 'edit all' section was used and permissions were checked each time before setting $uid.
 * The result is that the code is slightly longer and so more is loaded on bootstrap.
 * This is all technically unnecessary in terms of this module because the form doesn't render if it can't be used,
 * but it saves a lot of work for anyone who decides to render the form arbitrarily.
 *
 * @see facebook_status_update()
 * @see facebook_status_update_submit()
 */
function facebook_status_update_validate($form, &$form_state) {
  global $user;
  if ( user_access('edit own facebook_status') && !user_access('edit all facebook_status') ) {
    if ($form_state['values']['name'] == '' || $form_state['values']['name'] == ' ') {
      $last_status = db_result(db_query_range("SELECT status_fb FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $user->uid, 0, 1));
      if ( $last_status ) {
        $form_state['values']['name'] = $last_status;
      }
      else {
        form_set_error('', t('You must enter a status in order to save it.'));
      }
    }
  }
  //The only difference in this section is that $uid is used instead of $user->uid.
  else if (user_access('edit all facebook_status')) {
    if ($form_state['values']['name'] == '' || $form_state['values']['name'] == ' ') {
      $uid = $form_state['values']['uid'];
      if (!$uid) {
        if ( arg(0) == 'user' && is_numeric(arg(1)) ) {
          $uid = arg(1);
        }
        else if ( arg(0) == 'node' && is_numeric(arg(1)) ) {
          $uid = db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1)));
        }
        else {
          $uid = $user->uid;
        }
      }
      $last_status = db_result(db_query_range("SELECT status_fb FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $uid, 0, 1));
      if ( $last_status ) {
        $form_state['values']['name'] = $last_status;
      }
      else {
        form_set_error('', t('You must enter a status in order to save it.'));
      }
    }
  }
}

/**
 * Gets user statuses.
 * Warning: the status is not escaped, so developers still need to do validation to make sure there are no XSS attacks.
 * For optimal performance when finding the status for a single user, cast the user's uid to an array before calling this function.
 *
 * @param $fbs_uid
 *   Can be either a numeric value or an array.
 *   If it is a numeric value, the following applies:
 *     $fbs_uid is the UID for the user whose status(es) should be returned.
 *     If -1, the latest status updates for all users are returned, but only one status update is returned per user.
 *     If less than -1, all the latest status updates (for any user) are returned.
 *   If it is an array, $fbs_uid is an array of UIDs for users whose status(es) should be returned.
 *   If $fbs_uid is not passed it is treated as a single numeric value.  That value is assigned as follows:
 *     If the current page is a user profile, then we use the uid of the user whose profile is being viewed.
 *     If the current page is a node, then we use the uid of the author of that node.
 *     If the current page is neither a node nor a user profile, we use the current user's uid.
 * @param $num_results
 *   The number of results to return for the relevant user(s).
 *   If zero, all results are returned.
 *   If $fbs_uid is an array and $num_results is negative, only one result will be returned for each user specified, and no more than -($num_results) will be returned in total.
 * @return
 *   An array of arrays.  Each sub-array contains the status, status-posted-time, and uid of the user whose uid is passed to the function as $fbs_uid.
 *   Keys of the sub-arrays are status_fb, status_time, and fbs_uid, respectively.
 *   The top-level array holds all the sub-arrays: effectively, it is a list of different status updates.
 */
function facebook_status_get_status($fbs_uid = 0, $num_results = 1) {
  if (is_array($fbs_uid)) {
    $fbsu_array = $fbs_uid;
    $result = array();
    foreach ($fbsu_array as $fbs_uid) {
      if (!in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0)))) {
        if ( is_numeric($num_results) && $num_results < 0 ) {
          $query = db_query_range("SELECT sid, status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid, 0, 1);
        }
        else {
          $query = db_query("SELECT sid, status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid);
        }
        while ($row = db_fetch_array($query)) {
          $x = $row['sid'];
            //We can afford to break the loop because results should be ordered by sid, which is effectively the same as ordering by status_time.
            //This means that either we've run into blank statuses or there weren't any statuses to begin with.
            //And that means that empty($result[$x])  will return TRUE.
            if (!$row['status_time']) {
              break;
            }
          $result[$x] = $row;
          $result[$x]['fbs_uid'] = $fbs_uid;
        }
      }
    }
    if (empty($result)) {
      return;
    }
    krsort($result);
    //Resets the keys.
    $i = 0;
    foreach ($result as $value) {
      //Removes items from the array where the user is not allowed to have a status (in case the user added statuses before being disallowed from doing so).
      if (!in_array($value['fbs_uid'], variable_get('facebook_status_clear_user', array(0)))) {
        $output[$i] = $value;
        $i++;
      }
    }
    if (empty($output)) {
      return;
    }
    //Limits the number of results to $num_results.
    if (is_numeric($num_results) && $num_results < 0) {
      $num_results = -$num_results;
    }
    if (is_numeric($num_results) && $num_results > 0) {
      $i = 0;
      $final = array();
      //Lower the number of results to return if there aren't that many results so we don't end up with blank results.
      if ($num_results > count($output) ) {
        $num_results = count($output);
      }
      while ($i < $num_results) {
        $final[$i] = $output[$i];
        $i++;
      }
    }
    else {
      $final = $output;
    }
    return $final;
  }

  //This section is for numeric values of $fbs_uid.
  //We do it separately instead of casting $fbs_uid to an array in order to handle special cases (where $fbs_uid < 1).
  $result = array();
  if ( !$fbs_uid || !is_numeric($fbs_uid) ) {
    if ( arg(0) == 'user' && is_numeric(arg(1)) ) {
      $fbs_uid = arg(1);
    }
    else if ( arg(0) == 'node' && is_numeric(arg(1)) ) {
      $fbs_uid = db_result(db_query("SELECT uid FROM {node} WHERE nid = %d", arg(1)));
    }
    else {
      global $user;
      $fbs_uid = $user->uid;
    }
  }
  if ($fbs_uid < -1) {
    $duid = "";
  }
  else {
    $duid = "GROUP BY fbs_uid";
  }
  //$query is for displaying results for only one user, $query_2 is for displaying results for multiple users.  In $query_2, $duid controls grouping.
  if ( !is_numeric($num_results) ) {
    $num_results = 1;
    $query = db_query_range("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid, 0, 1);
    $query_2 = db_query_range("SELECT * FROM (SELECT uid as fbs_uid, status_fb, status_time, sid FROM {facebook_status} ORDER BY sid DESC) as x %s ORDER BY sid DESC", $duid, 0, 1);
  }
  else if (is_numeric($num_results) && $num_results == 0) {
    $query = db_query("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid);
    $query_2 = db_query("SELECT * FROM (SELECT uid as fbs_uid, status_fb, status_time, sid FROM {facebook_status} ORDER BY sid DESC) as x %s ORDER BY sid DESC", $duid);
  }
  else {
    //$num_results can only be negative if $fbs_uid is an array.
    if ($num_results < 0) {
      $num_results = -$num_results;
    }
    $query = db_query_range("SELECT status_fb, status_time FROM {facebook_status} WHERE uid = %d ORDER BY sid DESC", $fbs_uid, 0, $num_results);
    $query_2 = db_query_range("SELECT * FROM (SELECT uid as fbs_uid, status_fb, status_time, sid FROM {facebook_status} ORDER BY sid DESC) as x %s ORDER BY sid DESC", $duid, 0, $num_results);
  }
  if ( $fbs_uid > 0 && !in_array($fbs_uid, variable_get('facebook_status_clear_user', array(0))) ) {
    $result = array();
    $i = 0;
    while ($row = db_fetch_array($query)) {
      $result[$i] = $row;
      $result[$i]['fbs_uid'] = $fbs_uid;
      $i++;
    }
  }
  else if ( $fbs_uid < 0 ) {
    $result = array();
    while ($row = db_fetch_array($query_2)) {
      if (!in_array($row['fbs_uid'], variable_get('facebook_status_clear_user', array(0)))) {
        $result[] = $row;
      }
    }
  }
  else {
    //Build a blank status.
    $result[0] = array(
      'status_fb' => t("Error: this user is not allowed to have a status."),
      'status_time' => 0,
      'fbs_uid' => $fbs_uid,
    );
  }
  return $result;
}

/**
 * FAPI function for the administrative settings page.
 *
 * @ingroup forms
 * @see facebook_status_admin_validate()
 * @see facebook_status_admin_submit()
 */
function facebook_status_admin() {

  $form['fbs_general'] = array(
    '#type' => 'fieldset',
    '#title' => t('General settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => -3,
    '#tree' => TRUE,
  );
  $form['fbs_general']['facebook_status_mode'] = array(
    '#type' => 'checkbox',
    '#title' => t('Facebook Mode'),
    '#default_value' => variable_get('facebook_status_mode', 1),
    '#description' => t("Facebook Mode makes this module work like Facebook, where the user's username is appended to the front of the status.  Default is On."),
  );
  $form['fbs_general']['facebook_status_ajax'] = array(
    '#type' => 'checkbox',
    '#title' => t('Slide Effect'),
    '#default_value' => variable_get('facebook_status_ajax', 1),
    '#description' => t("With this enabled, users who have permission to edit statuses can click on the status to see the edit box drop down.  This minimizes the space that Facebook Status takes up.  Default is On."),
  );

  $form['fbs_lengths'] = array(
    '#type' => 'fieldset',
    '#title' => t('Status length'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => -2,
    '#tree' => TRUE,
  );
  $form['fbs_lengths']['facebook_status_field_length'] = array(
    '#type' => 'textfield',
    '#title' => t('Length of the Status textfield'),
    '#default_value' => variable_get('facebook_status_field_length', 30),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t("30 is standard length for a sidebar block (and the default); 72 is standard for most content and footer blocks.")
  );
  $form['fbs_lengths']['facebook_status_length'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum length of a status'),
    '#default_value' => variable_get('facebook_status_length', 192),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t("192 is the default; 255 is the maximum; no higher than 240 is recommended.  No statuses may be longer than this.")
  );
  $form['fbs_lengths']['facebook_status_max_block_len_all'] = array(
    '#type' => 'textfield',
    '#title' => t('Shorten statuses in the Facebook Status Recent Updates block to this length'),
    '#default_value' => variable_get('facebook_status_max_block_len_all', variable_get('facebook_status_length', 192)),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t("The maximum status length (above) is the default and maximum; 25 is the minimum.  You may want to lower this if you have more than one status showing on the block.")
  );
  if (module_exists('user_relationships')) {
    $form['fbs_lengths']['facebook_status_max_block_len'] = array(
      '#type' => 'textfield',
      '#title' => t('Shorten statuses in the Facebook Status UR Recent Updates to this length'),
      '#default_value' => variable_get('facebook_status_max_block_len', variable_get('facebook_status_length', 192)),
      '#size' => 3,
      '#maxlength' => 3,
      '#description' => t("The maximum status length (above) is the default and maximum; 25 is the minimum.  You may want to lower this if you have more than one status showing on the block.")
    );
  }

  $form['fbs_number'] = array(
    '#type' => 'fieldset',
    '#title' => t('Number of statuses'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => -1,
    '#tree' => TRUE,
  );
  $form['fbs_number']['facebook_status_max_num_block_stats_all'] = array(
    '#type' => 'textfield',
    '#title' => t('The maximum number of statuses to show in the Facebook Status Recent Updates block'),
    '#default_value' => variable_get('facebook_status_max_num_block_stats_all', 5),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t("5 is the default, 1 is the minimum.")
  );
  if (module_exists('user_relationships')) {
    $form['fbs_number']['facebook_status_max_num_block_stats'] = array(
      '#type' => 'textfield',
      '#title' => t('The maximum number of statuses to show in the Facebook Status UR Recent Updates block'),
      '#default_value' => variable_get('facebook_status_max_num_block_stats', 5),
      '#size' => 3,
      '#maxlength' => 3,
      '#description' => t("5 is the default, 1 is the minimum.")
    );
  }

  $form['fbs_misc'] = array(
    '#type' => 'fieldset',
    '#title' => t('Miscellaneous'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 0,
    '#tree' => TRUE,
  );
  $form['fbs_misc']['facebook_status_clear_user_records_string'] = array(
    '#type' => 'textfield',
    '#title' => t('Remove all statuses for these users'),
    '#default_value' => variable_get('facebook_status_clear_user_records_string', implode(',', variable_get('facebook_status_clear_user_records', array(0)))),
    '#size' => 72,
    '#maxlength' => 255,
    '#description' => t("Use zero for none.  Separate each UID with a comma: 1,2,3")
  );
  $form['fbs_misc']['facebook_status_clear_user_string'] = array(
    '#type' => 'textfield',
    '#title' => t('Specify the UIDs of users who are not allowed to have statuses'),
    '#default_value' => variable_get('facebook_status_clear_user_string', implode(',', variable_get('facebook_status_clear_user', array(0)))),
    '#size' => 72,
    '#maxlength' => 255,
    '#description' => t("Use zero for none.  Separate each UID with a comma: 1,2,3")
  );
  variable_set('facebook_status_clear_all', 'none');
  $form['fbs_misc']['facebook_status_clear_all'] = array(
    '#type' => 'select',
    '#title' => t('Delete'),
    '#default_value' => variable_get('facebook_status_clear_all', 'none'),
    '#description' => t("Deletes status updates from the database.  CANNOT BE UNDONE."),
    '#options' => array(
      'none' => 'Nothing',
      'all' => 'All status updates',
      'old' => 'All but the latest status update for each user',
    ),
  );
  if (module_exists('advanced_forum') && module_exists('user_relationships')) {
    $fbsur = facebook_status_rel_types(TRUE);
    $form['fbs_misc']['facebook_status_advf'] = array(
      '#type' => 'select',
      '#title' => t('Only show status on Advanced Forum posts to users with this relationship to the poster'),
      '#default_value' => variable_get('facebook_status_advf', -2),
      '#description' => t("Advanced Forum can display a user's Status on their post.  If you would like to only show the status to users with whom the poster has a certain relationship, set that relationship here."),
      '#options' => $fbsur,
    );
  }

  //Normally this is unnecessary, but for unknown reasons the form suddenly decided not to recognize the _submit function, so we specify it directly.
  $form['#submit'][] = 'facebook_status_admin_submit';
  return system_settings_form($form);
}

function facebook_status_rel_types($advf = FALSE) {
  if (module_exists('user_relationships')) {
    return facebook_status_ur_types($advf);
  }
  return;
}

/**
 * Returns user relationship types.
 */
function facebook_status_ur_types($advf = FALSE) {
  $fbsur_result = db_query("SELECT plural_name, rtid FROM {user_relationship_types}");
  $fbsur = array();
  while ($row = db_fetch_array($fbsur_result)) {
    $i = $row['rtid'];
    $fbsur[$i] = $row['plural_name'];
  }
  if ($advf) {
    $fbsur[-1] = t('Any relationship');
    $fbsur[-2] = t('Ignore relationships');
  }
  return $fbsur;
}

/**
 * FAPI validate function for facebook_status_admin().
 * Implementation of hook_validate().
 *
 * @see facebook_status_admin()
 * @see facebook_status_admin_submit()
 */
function facebook_status_admin_validate($form, &$form_state) {
  if (!(is_numeric($form_state['values']['fbs_lengths']['facebook_status_field_length']) && $form_state['values']['fbs_lengths']['facebook_status_field_length'] <= variable_get('facebook_status_length', 192) && $form_state['values']['fbs_lengths']['facebook_status_field_length'] > 1)) {
    form_set_error('', t('Please enter a number between 1 and the maximum status length, inclusive, for the length of the status textfield.'));
  }
  if (!(is_numeric($form_state['values']['fbs_lengths']['facebook_status_length']) && $form_state['values']['fbs_lengths']['facebook_status_length'] <= 255 && $form_state['values']['fbs_lengths']['facebook_status_length'] > 1)) {
    form_set_error('', t('Please enter a number between 1 and 255, inclusive, for the maximum status length.'));
  }
  if (!(is_numeric($form_state['values']['fbs_lengths']['facebook_status_max_block_len_all']) && $form_state['values']['fbs_lengths']['facebook_status_max_block_len_all'] >= 25)) {
    form_set_error('', t('Please enter a number between 25 and the maximum status length, inclusive, for the maximum length of statuses in the Facebook Status Recent Updates block.'));
  }
  if (module_exists('user_relationships')) {
    if (!(is_numeric($form_state['values']['fbs_lengths']['facebook_status_max_block_len']) && $form_state['values']['fbs_lengths']['facebook_status_max_block_len'] >= 25)) {
      form_set_error('', t('Please enter a number between 25 and the maximum status length, inclusive, for the maximum length of statuses in the Facebook Status UR Recent Updates block.'));
    }
  }
  if (!(is_numeric($form_state['values']['fbs_number']['facebook_status_max_num_block_stats_all']) && $form_state['values']['fbs_number']['facebook_status_max_num_block_stats_all'] >= 1)) {
    form_set_error('', t('Please enter a number above zero for the maximum number of statuses to show in the Facebook Status Recent Updates block.'));
  }
  if (module_exists('user_relationships')) {
    if (!(is_numeric($form_state['values']['fbs_number']['facebook_status_max_num_block_stats']) && $form_state['values']['fbs_number']['facebook_status_max_num_block_stats'] >= 1)) {
      form_set_error('', t('Please enter a number above or equal to 1 for the maximum number of statuses to show in the Facebook Status UR Recent Updates block.'));
    }
  }
  $temp = explode(',', variable_get('facebook_status_clear_user_string', implode(',', variable_get('facebook_status_clear_user', array(0)))));
  foreach ($temp as $value) {
    $is_user = FALSE;
    if ( $value > 0 && is_numeric($value) ) {
      $is_user = $value;
    }
    if (!($is_user || $value == 0)) {
      form_set_error('', t('Each value you enter in the disallowed users box must be a User ID, and each UID must be serparated by nothing more than a comma.  The UID is the number that shows up in the URL after "[domain]/user/" on profile pages.'));
    }
  }
  $temp = explode(',', variable_get('facebook_status_clear_user_records_string', implode(',', variable_get('facebook_status_clear_user_records', array(0)))));
  foreach ($temp as $value) {
    $is_user = FALSE;
    if ( $value > 0 && is_numeric($value) ) {
      $is_user = $value;
    }
    if (!($is_user || $value == 0)) {
      form_set_error('', t('Each value you enter in the clear-user-statuses box must be a User ID, and each UID must be serparated by nothing more than a comma.  The UID is the number that shows up in the URL after "[domain]/user/" on profile pages.'));
    }
  }
}

/**
 * FAPI submit function for facebook_status_admin().
 * Implementation of hook_submit().
 *
 * @see facebook_status_admin()
 * @see facebook_status_admin_validate()
 */
function facebook_status_admin_submit($form, &$form_state) {
  variable_set('facebook_status_clear_user', explode(',', variable_get('facebook_status_clear_user_string', '0')));
  if ($form_state['values']['fbs_misc']['facebook_status_clear_all'] == 'all') {
    db_query("TRUNCATE TABLE {facebook_status}");
    drupal_set_message(t('All statuses cleared.'));
  }
  //Deletes all statuses except the most current one for each user.
  else if ($form_state['values']['fbs_misc']['facebook_status_clear_all'] == 'old') {
    //We go through this extra process because a query can't select from a table that it's also deleting from.  Otherwise, we could use "sid NOT IN [subquery]."
    $temp = db_query("SELECT MAX(sid) as sid FROM {facebook_status} GROUP BY uid");
    $nsids = '';
    while ($value = db_fetch_array($temp)) {
      $nsids .= " AND sid != ". $value['sid'];
    }
    //Removes first " AND ".
    $nsids = drupal_substr($nsids, 5);
    db_query("DELETE FROM {facebook_status} WHERE %s ORDER BY sid ASC", $nsids);
    drupal_set_message(t('All statuses except the most recent one were cleared for each user.'));
  }
  variable_set('facebook_status_clear_user_records', explode(',', variable_get('facebook_status_clear_user_records_string', '0')));
  $temp = variable_get('facebook_status_clear_user_records', explode(',', variable_get('facebook_status_clear_user_records_string', '0')));
  foreach ($temp as $value) {
    if ($value != 0) {
      db_query("DELETE FROM {facebook_status} WHERE uid = %d", $value);
      $user2 = user_load(array('uid' => $value));
      $name = $user2->name;
      $message = t('All statuses were cleared for ') . $name;
      drupal_set_message($message);
    }
  }

  //Sets variables because the form refuses to do it for us! >:(
  $values = array();
  $values['fbs_general'] = $form_state['values']['fbs_general'];
  $values['fbs_lengths'] = $form_state['values']['fbs_lengths'];
  $values['fbs_number'] = $form_state['values']['fbs_number'];
  $values['fbs_misc'] = $form_state['values']['fbs_misc'];
  foreach ($values as $key => $value) {
    variable_set($key, $value);
  }
  variable_del('facebook_status_clear_user_records_string');
  variable_del('facebook_status_clear_user_records');
}

/**
 * Implementation of hook_menu().
 */
function facebook_status_menu() {

  $items = array();

  $items['admin/settings/facebook_status'] = array(
    'title' => 'Facebook Status settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('facebook_status_admin'),
    'access arguments' => array('access administration pages'),
    'description' => 'Allows administrators to adjust certain display settings for Facebook Status.',
  );

  return $items;
}

/**
 * Gets a user's friends and sends them to facebook_status_get_status().  For use with facebook_status_get_rel_status mainly.
 *
 * @param $ur_rtid
 *   The relationship type ID (rtid) to use when determining which users the current user relates to.
 *   If a rtid is not passed, this function uses the default relationship specified on the Facebook Status settings page.
 * @param $number
 *   The number of statuses returned.
 *   If not passed, defaults to the setting from the Facebook Status settings page.
 * @param $grouping
 *   If TRUE, only one status update is returned per user.
 *   If FALSE, all available updates are returned per user.
 * @return
 *   An array of arrays per the return value of facebook_status_get_status().  Only status updates from users with whom the current user has a certain relationship are returned.
 */
function facebook_status_get_ur_status($ur_rtid = -1, $number = 0, $grouping = TRUE) {
  if (!is_numeric($number) || $number < 0) {
    $number = 0;
  }
  if (!$number) {
    $number = variable_get('facebook_status_max_num_block_stats', 5);
  }
  if ($ur_rtid = -1) {
    $ur_rtid = variable_get('facebook_status_ur_type', 1);
  }
  if (db_result(db_query("SELECT COUNT(*) FROM {user_relationship_types}"))) {
    global $user;
    //Dynamically build queries based on whether the relevant relationship type is one-way and/or requires approval.
    $ur_object = db_fetch_array(db_query("SELECT is_oneway, requires_approval FROM {user_relationship_types} WHERE rtid = %d", $ur_rtid));
    if ($ur_object['is_oneway'] == 1) {
      $ur_oneway_fbjoin = "fb.uid = ur.requester_id";
      $ur_oneway_urwhere = "ur.requester_id = ". $user->uid;
    }
    else {
      $ur_oneway_fbjoin = "(fb.uid = ur.requester_id OR fb.uid = ur.requestee_id)";
      $ur_oneway_urwhere = "(ur.requester_id = ". $user->uid ." OR ur.requestee_id = ". $user->uid .")";
    }
    if ($ur_object['requires_approval'] = 1) {
      $ur_requires_approval = "AND (ur.approved = 1)";
    }
    else {
      $ur_requires_approval = "";
    }
    $disallow = "";
    foreach (variable_get('facebook_status_clear_user', array(0)) as $value) {
      $disallow .= " AND fb.uid != ". $value;
    }
    $user_rel = db_query("
    SELECT fb.uid
    FROM {facebook_status} as fb
    LEFT JOIN {user_relationships} AS ur
      ON %s
    WHERE %s
      %s
      AND (ur.rtid = %d)
      %s
      AND fb.uid <> %d
    GROUP BY uid
    ", $ur_oneway_fbjoin, $ur_oneway_urwhere, $ur_requires_approval, $ur_rtid, $disallow, $user->uid);

    while ($row = db_fetch_array($user_rel)) {
      $uid_list[] = $row['uid'];
    }
    if ($grouping) {
      $number = -abs($number);
    }
    else {
      $number = abs($number);
    }
    return facebook_status_get_status($uid_list, $number);
  }
  else {
    return;
  }
}

/**
 * Renders a list of users' statuses.  Intended for use with _get_status() functions.
 *
 * @param $fbs_list
 *   An array of the type returned by facebook_status_get_status: each element should be a sub-array with keys 'status_fb', 'status_time', and 'fbs_uid'.
 * @return
 *   HTML for rendering a list of users and their statuses.
 */
function facebook_status_list_render($fbs_list) {
  global $user;
  if (!empty($fbs_list)) {
    //Count by $i instead of using db_query_range() so we can exclude the current user and still end up with the right number of results.
    foreach ($fbs_list as $row) {
      $user2 = user_load(array('uid' => $row['fbs_uid']));
      if ($row['fbs_uid'] != $user->uid) {
        if (time() - $row['status_time'] < 60) {
          $time = t("a moment");
        }
        else {
          $time = format_interval(time() - $row['status_time'], 1);
        }
        $status = $row['status_fb'];
        if ($status) {
          if (drupal_strlen($row['status_fb']) > variable_get('facebook_status_max_block_len', variable_get('facebook_status_length', 192))) {
            $status = drupal_substr($row['status_fb'], 0, variable_get('facebook_status_max_block_len', variable_get('facebook_status_length', 192))) .'...';
          }
          $list[] = t("<span class='fbs_list_item' title='@username @status_long'> !user @status_short <div class='submitted'>!time ago</div></span>", array('@username' => $user2->name, '@status_long' => $row['status_fb'], '!user' => theme('username', $user2), '@status_short' => $status, '!time' => $time, 1));
        }
      }
    }
    if ($list) {
      return theme_item_list($list, NULL, 'ul', array('div' => 'facebook_status_list_block'));
    }
  }
}

/**
 * Implementation of hook_user().
 */
function facebook_status_user($op, &$edit, &$account) {
  if ($op == 'delete') {
    //Remove abandoned statuses from the database on user account deletion.
    db_query('DELETE FROM {facebook_status} WHERE uid = %d', $account->uid);
  }
  if ($op == 'load') {
    $status = facebook_status_get_status($account->uid);
    $s['status_fb'] = $status[0]['status_fb'];
    $s['status_time'] = $status[0]['status_time'];
    $account->facebook_status = $s;
  }
}

/**
 * Integration with Advanced Forum.
 */
function facebook_status_advf($account) {
  global $user;
  if (!$account->uid) {
    return;
  }
  $friends = TRUE;
  if ($account->uid != $user->uid) {
    $friends = facebook_status_advf_rel($account);
  }
  if ($user->uid && $friends) {
    $status = facebook_status_get_status($account->uid);
    if ($status[0]['status_fb']) {
      $so = '';
      $user2 = user_load(array('uid' => $account->uid));
      if (drupal_strlen($status[0]['status_fb']) > 32) {
        $so = ' title="'. check_plain($user2->name .' '. $status[0]['status_fb']) .'"';
        $status[0]['status_fb'] = drupal_substr($status[0]['status_fb'], 0, 32) .'...';
      }
      $output = '<p class="submitted"'. $so .'>'. theme('username', $user2) .' '. check_plain($status[0]['status_fb']) .'</p>';
      return $output;
    }
  }
}

function facebook_status_advf_rel($account) {
  if (module_exists('user_relationships')) {
    return facebook_status_advf_ur($account);
  }
  return TRUE;
}

function facebook_status_advf_ur($account) {
  global $user;
  //Any relationship.
  if (variable_get('facebook_status_advf', -2) == -1) {
    $friends = db_result(db_query("SELECT COUNT(requester_id) FROM {user_relationships} WHERE (requester_id = %d OR requestee_id = %d) AND (requester_id = %d OR requestee_id = %d)", $account->uid, $account->uid, $user->uid, $user->uid));
  }
  //Ignore relationships.
  else if (variable_get('facebook_status_advf', -2) == -2) {
    $friends = TRUE;
  }
  else {
    $approve = db_result(db_query("SELECT requires_approval FROM {user_relationship_types} WHERE rtid = %d", variable_get('facebook_status_advf', -2)));
    if ($approve) {
      $friends = db_result(db_query("SELECT COUNT(requester_id) FROM {user_relationships} WHERE (requester_id = %d OR requestee_id = %d) AND (requester_id = %d OR requestee_id = %d) AND rtid = %d AND approved = 1", $account->uid, $account->uid, $user->uid, $user->uid, variable_get('facebook_status_advf', -2)));
    }
    else {
      $friends = db_result(db_query("SELECT COUNT(requester_id) FROM {user_relationships} WHERE (requester_id = %d OR requestee_id = %d) AND (requester_id = %d OR requestee_id = %d) AND rtid = %d", $account->uid, $account->uid, $user->uid, $user->uid, variable_get('facebook_status_advf', -2)));
    }
  }
  return $friends;
}

/*
 * NoticeFeed Integration.
 */
function fbs_notice_insert($uid) {
  if (module_exists("notice")) {
    $new_id = db_last_insert_id('facebook_status', 'sid');
    $notice_array = array(
      'nb_type' => NOTICE_NORMAL,
      'module_type' => "facebook_status",
      'source_uid' => $uid,
      'prime_id' => $new_id,
      'op' => "facebook_status_add",
    );
    noticeapi_notice_add("facebook_status", $notice_array);
  }
}

function facebook_status_notice($op, $type, $record) {
  switch ($op) {
    case 'feed':
      $sql = "SELECT * FROM {facebook_status} WHERE sid = %d";
      $record2 = db_fetch_object(db_query($sql, $record->prime_id));
      $output = '<div class="notice-'. $record->module_type .'">';
      $user = user_load(array('uid' => $record2->uid));
      $output .= t('%user has a new status.', array('%user' => $user->name));
      $output .= '</div>';
      return $output;
      break;
  };
}