<?php
// $Id$

/**
 * @file
 *   Integrates Activity 2 with Facebook-style Statuses.
 */

/**
 * Implementation of hook_facebook_status_delete().
 */
function fbss_activity_facebook_status_delete($sid) {
  $result = db_query("SELECT aid FROM {activity} WHERE type = 'facebook_status' AND eid = %d", $sid);
  $records = array();
  while ($record = db_fetch_object($result)) {
    $records[] = $record->aid;
  }
  if (!empty($records)) {
    activity_delete($records);
  }
}

/**
 * Implementation of hook_activity_info().
 */
function facebook_status_activity_info() {
  $info = new stdClass();
  $info->api = 2;
  $info->name = 'facebook_status';
  $info->object_type = 'facebook_status';
  $info->eid_field = 'sid';
  $info->objects = array('Recipient' => 'facebook_status', 'Sender' => 'sender');
  $hooks = array('fbss_deleted', 'fbss_edited', 'fbss_submitted', 'fbss_submitted_other');
  foreach (facebook_status_all_contexts() as $type => $details) {
    if ($type == 'user') {
      $hooks[] = 'fbss_submitted_user_self';
      $hooks[] = 'fbss_submitted_user_other';
    }
    else {
      $hooks[] = 'fbss_submitted_'. $type;
    }
  }
  $info->hooks = array('facebook_status' => $hooks);
  $info->realms = array('facebook_status_sender' => 'Facebook-style Statuses Sender', 'facebook_status_recipient' => 'Facebook-style Statuses Recipient');
  return $info;
}

/**
 * Implementation of hook_activity_grants().
 */
function facebook_status_activity_grants($activity) {
  $realms = array();
  if ($activity->type == 'facebook_status') {
    $realms['facebook_status_sender'] = array($activity->uid);
    $result = db_fetch_object(db_query("SELECT recipient FROM {facebook_status} WHERE sid = %d", $activity->eid));
    $realms['facebook_status_recipient'] = array($result->recipient);
  }
  return $realms;
}

/**
 * Implementation of hook_activity_access_grants().
 */
function facebook_status_activity_access_grants($account) {
  return array(
    'facebook_status_sender' => array($account->uid),
    'facebook_status_recipient' => array($account->uid),
  );
}
